### ISSUE TITLE
Power header upside down?

### ISSUE THREAD

**Issue by KeLaiFu** [squaresolid/benjolin_gorga#2]
I'm just checking my revision of your layout before I send it to jlc and unless I am misunderstanding it, isn't the power header upside down?
I checked your photos and the finished module has the header the same way as the PCB layout so now I am very confused.

**Comment by squaresolid** [comment]
Hi!
Thanks for the checking. yes the power header is upside down, this is how i got the schematic from forestcaver. So you just need to flip it. Which LM did I remove?

**Comment by KeLaiFu** [comment]
Ah, I see, I checked with the forestcaver layout after posting here and noticed he didn't add the keyed header so I guess it doesn't matter in his case. I edited the question about the LM, i was just being dumb and didn't notice the other one...
Thanks again!
